### ISSUE TITLE
cannot install!!

### ISSUE THREAD

**Issue by Khalilsqu** [hadrienmichel/SardineReborn#2] opened 2024-03-04 12:40 UTC
```
C:\Users\kalho\Downloads\SardineReborn-master>conda env create -f seismic.yml
Channels:
 - gimli
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - aiohttp==3.8.3=py37h8052db5_0
  - aom==3.5.0=hf0c8a7f_0
  - boost==1.72.0=py37hc4fef25_1
  - boost-cpp==1.72.0=h179ae3a_7
  - brotlipy==0.7.0=py37h69ee0a8_1004
  - bzip2==1.0.8=h0d85af4_4
  - c-ares==1.18.1=h0d85af4_0
  - ca-certificates==2022.12.7=h033912b_0
  - cffi==1.15.1=py37h7346b73_1
  - cryptography==37.0.4=py37h0169fcd_0
  - curl==7.87.0=haf73cf8_0
  - double-conversion==3.2.0=hf0c8a7f_1
  - eigen==3.4.0=h940c156_0
  - expat==2.5.0=hf0c8a7f_0
  - ffmpeg==4.4.2=gpl_hff0bab5_109
  - fontconfig==2.14.2=h5bb23bf_0
  - freetype==2.12.1=h3f81eb7_1
  - frozenlist==1.3.3=py37h6c40b1e_0
  - gettext==0.21.1=h8a4c099_0
  - gl2ps==1.4.2=h4cff582_0
  - glew==2.1.0=h046ec9c_2
  - glib==2.74.1=hbc0c0cd_1
  - glib-tools==2.74.1=hbc0c0cd_1
  - gmp==6.2.1=h2e338ed_0
  - gnutls==3.7.8=h207c4f0_0
  - gst-plugins-base==1.22.0=h37e1711_0
  - gstreamer==1.22.0=h1d18e73_0
  - hdf4==4.2.15=h7aa5921_5
  - hdf5==1.12.2=nompi_h70e9adf_101
  - icu==70.1=h96cf925_0
  - importlib-metadata==4.11.4=py37hf985489_0
  - jpeg==9e=hac89ed1_2
  - jsoncpp==1.9.5=h940c156_1
  - kiwisolver==1.4.4=py37h229a17a_0
  - krb5==1.20.1=h0165f36_0
  - lame==3.100=hb7f2c08_1003
  - lcms2==2.14=h90f4b2a_0
  - lerc==4.0.0=hb486fe8_0
  - libaec==1.0.6=hf0c8a7f_1
  - libblas==3.9.0=16_osx64_openblas
  - libcblas==3.9.0=16_osx64_openblas
  - libclang==13.0.1=default_he082bbe_0
  - libcurl==7.87.0=haf73cf8_0
  - libcxx==14.0.6=hccf4f1f_0
  - libdeflate==1.14=hb7f2c08_0
  - libedit==3.1.20191231=h0678c8f_2
  - libev==4.33=haf1e3a3_1
  - libffi==3.4.2=h0d85af4_5
  - libgfortran==5.0.0=11_3_0_h97931a8_27
  - libgfortran5==11.3.0=h082f757_27
  - libglib==2.74.1=h4c723e1_1
  - libiconv==1.17=hac89ed1_0
  - libidn2==2.3.4=hb7f2c08_0
  - liblapack==3.9.0=16_osx64_openblas
  - libllvm13==13.0.1=h64f94b2_2
  - libnetcdf==4.8.1=nompi_hebd45d5_104
  - libnghttp2==1.51.0=h0dd9d14_0
  - libogg==1.3.4=h35c211d_1
  - libopenblas==0.3.21=openmp_h429af6e_3
  - libopus==1.3.1=hc929b4f_1
  - libpng==1.6.39=ha978bb4_0
  - libpq==15.1=hdbdeef1_3
  - libsqlite==3.40.0=ha978bb4_0
  - libssh2==1.10.0=h7535e13_3
  - libtasn1==4.19.0=hb7f2c08_0
  - libtheora==1.1.1=h0d85af4_1005
  - libtiff==4.4.0=h6268bbc_5
  - libunistring==0.9.10=h0d85af4_0
  - libvorbis==1.3.7=h046ec9c_0
  - libvpx==1.11.0=he49afe7_3
  - libwebp-base==1.2.4=h775f41a_0
  - libxcb==1.13=h0d85af4_1004
  - libxml2==2.9.14=hea49891_4
  - libxslt==1.1.35=h5b33f42_0
  - libzip==1.9.2=h3ad4413_1
  - libzlib==1.2.13=hfd90126_4
  - llvm-openmp==15.0.7=h61d9ccf_0
  - loguru==0.6.0=py37hf985489_1
  - lxml==4.9.1=py37h65b224f_0
  - lz4-c==1.9.4=hf0c8a7f_0
  - matplotlib-base==3.2.2=py37hddda452_1
  - metis==5.1.0=h2e338ed_1006
  - mpfr==4.1.0=h0f52abe_1
  - multidict==6.0.2=py37hca72f7f_0
  - mysql-common==8.0.31=h7ebae80_0
  - mysql-libs==8.0.31=hc37e033_0
  - ncurses==6.3=h96cf925_1
  - nettle==3.8.1=h96f3785_1
  - nlohmann_json==3.11.2=hbbd2c75_0
  - nspr==4.35=hea0b92c_0
  - nss==3.78=ha8197d3_0
  - numpy==1.18.5=py37h7687784_0
  - obspy==1.3.0=py37h4105427_0
  - openblas==0.3.21=openmp_hbefa662_3
  - openh264==2.3.1=hf0c8a7f_2
  - openjpeg==2.5.0=h5d0d7b0_1
  - openssl==1.1.1t=hfd90126_0
  - p11-kit==0.24.1=h65f8906_0
  - pcre2==10.40=h1c4e4bc_0
  - pillow==9.2.0=py37ha6ba2b9_2
  - pluggy==1.0.0=py37hf985489_3
  - proj==9.1.0=hcbd9701_0
  - pthread-stubs==0.4=hc929b4f_1001
  - pugixml==1.11.4=he49afe7_0
  - pygimli==1.1.0=np118py37h0a44026_1
  - pyqt==5.15.7=py37h6d02c96_0
  - pyqt5-sip==12.11.0=py37h453a0d4_0
  - pysocks==1.7.1=py37hf985489_5
  - pytest==7.2.0=py37hf985489_0
  - python==3.7.12=haf480d7_100_cpython
  - qt-main==5.15.8=h1d3b3f8_6
  - readline==8.1.2=h3899abd_0
  - scipy==1.7.3=py37h4e3cf02_0
  - sip==6.6.2=py37hc568d09_0
  - sqlalchemy==1.3.24=py37h69ee0a8_1
  - sqlite==3.40.0=h9ae0607_0
  - suitesparse==5.10.1=h7aff33d_1
  - svt-av1==1.3.0=hf0c8a7f_0
  - tbb==2021.7.0=hb8565cd_1
  - tbb-devel==2021.7.0=hb8565cd_1
  - tetgen==1.6.0=hb1e8313_0
  - tk==8.6.12=h5dbffcc_0
  - tornado==6.2=py37h994c40b_0
  - utfcpp==3.2.3=h694c41f_0
  - vtk==9.2.2=qt_py37he90502e_202
  - x264==1!164.3095=h775f41a_2
  - x265==3.5=hbb4e6a2_3
  - xorg-libxau==1.0.9=h35c211d_0
  - xorg-libxdmcp==1.1.3=h35c211d_0
  - xz==5.2.6=h775f41a_0
  - yarl==1.7.2=py37h69ee0a8_2
  - zlib==1.2.13=hfd90126_4
  - zstd==1.5.2=hbc0c0cd_6

Current channels:

  - https://conda.anaconda.org/gimli/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by hadrienmichel** [comment] 2024-03-22 09:37
Hi @Khalilsqu ! 

Thanks for raising this issue. I could reproduce it on my machine and needed to alter the environment description in order to install it. 

I pushed a new version ([v0.4.4](https://github.com/hadrienmichel/SardineReborn/tree/v0.4.4)) with a new env that should solve the issue you are having.

Please, note that solving the environment took a rather long time on my machine (1 to 2 hours). 

I hope this helps.

**Comment by hadrienmichel** [comment] 2024-06-04 12:23
Hi @Khalilsqu, 

Since you did not update on this issue, I consider that it has been fixed in the last version and close it.

Feel free to re-open it in case the issue had not been solved. 

Best,

Hadrien

**Closed as completed by hadrienmichel** 2024-06-04 12:23 UTC
